name: newrelic workflow

on:
  push:
  schedule:
    - cron: '35 9 * * *'  # 每天 0 点执行

jobs:
  execute-python-source-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install requests

    - name: Execute Python Source Code
      run: python3 monitor.py
