name: newrelic workflow

on:
  schedule:
    - cron: '30 1 * * *'  # 每天北京时间 9:30 执行

jobs:
  execute-python-source-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install requests

    - name: Execute Python Source Code
      run: python3 monitor.py
      env: #设置secrets的环境变量
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        API_KEY: ${{ secrets.API_KEY }}
